### PR TITLE
Make extension compatible with TYPO3 v12 and PHP 8.2

### PR DESCRIPTION
**Pull request by hannesbochmann**
As the PR #174 does not contain PHP 8.2 support which is essential for TYPO3 12, I added it. Furthermore I fixed some minor issues in the BE module and incorporated https://github.com/datamintsGmbH/t3ext-ig_ldap_sso_auth/pull/1 .

To be clear. The main contribution still comes from datamints. So thanks for their effort.

### CODE REVIEW

**Comment by mschwemer** [comment]
Thanks for your work. 

In my fork, I added other bugfix to make the creation of fe user records work as expected. Currently the replaced TYPO3_MODE is always `BE`.  Maybe you want to integrate it here too. 

Besides that: I do not think, that @xperseguers will merge the PR regarding his support strategy. At the same time, I don't like it to run an extension on a fork. 

What do you think about joining forces to make it compatible for v11 *and* v12? I probably would get some time from my PM and / or customers to get that "fixed".

**Comment by hannesbochmann** [comment]
I could invest some more time but I'm afraid not that much.

**Comment by sk-foresite** [comment]
Hey, thanks for providing a TYPO3 v12 Version of this extension!

I found an issue with the initialization of the backend configuration. It always seems to use the frontend configuration because the check against the mode is wrong.

I commited a fix in my branch:
https://github.com/sk-foresite/t3ext-ig_ldap_sso_auth/commit/f3cacb020f73e6ed213f479180186277a749a8bb

**Comment by hannesbochmann** [comment]
I cherry picked your commit. Thanks for the contribution.

**Comment by xperseguers** [comment]
I incorporated many of the suggested changes (possibly including from other forks as well) manually. Thanks for your contribution.

Closing this PR as it looks like everything that was to be taken into account as been taken into account. Please use master branch (again) which supports TYPO3 v11 and v12 and will soon be tested against v13 as well before releasing.

Thanks again!

**Pull request closed without merging**
