### PR TITLE
[Bugfix] Remove getLanguageService from Import Task for TYPO3 10 compatibility

### PR DESCRIPTION
**Pull request by stauer**
Function declaration is not valid any more. Using default function from AbstractTask instead.

### CODE REVIEW

**Comment by stauer** [comment]
Good point ;-)
I think there are 2 options:

- Releasing a version with minor TYPO3 version requirement of 10.4 LTS, or
- inserting a condition inside ext_localconf.php, checking TYPO3 Version and therefore registering different Task-Classes

What do you think?

**Comment by xperseguers** [comment]
What I think is that you did not create a bug report, so I can only guess what the problem is you try to fix. What's exactly the problem in v10, why does it crash? I can't understand by reading, I need to dig into the code...

Well, by digging, I still don't see what is broken.

**Comment by stauer** [comment]
The function is not compatible any more with TYPO3 10 core. It's not overwritten correctly. Trying to add scheduler task leads to an PHP fatal error.

**Comment by xperseguers** [comment]
should be fixed by 36acf5cc0b2c8a08ebbde38da79b18707fad28cb with compatibility with former versions as well.

**Comment by xperseguers** [comment]
Cannot reproduce anymore.

**Pull request closed without merging**
